### ISSUE TITLE
cannot locate package xfsettingsd

### ISSUE THREAD

**Issue by moedemonic** [adi1090x/termux-desktop#1]
I ran the command to install all the dependancies, and got an error:
"E: Unable to locate package xfsettingsd"
This is on a fresh install of termux on Android 9, Galaxy S8

**Comment by x60sepia** [comment]
Yea I got the same error, than search for the package name  and find out actually the package name is xfce4-settings. See https://manpages.ubuntu.com/manpages/trusty/man1/xfsettingsd.1.html, and yes I know its ubuntu's man page but turns out the package name is the same in termux. I guess because both use apt.

**Comment by moedemonic** [comment]
oh ok, thanks!

**Comment by x60sepia** [comment]
Your welcome. I just happens to tried out and already thought might someone else got the same problem at least I can let them know.
