### ISSUE TITLE
"Error installing bc, terminating.."

### ISSUE THREAD

**Issue by Faris0520** [adi1090x/termux-desktop#106]
![Screenshot_2022-01-08-18-43-30-392_com termux](https://user-images.githubusercontent.com/65797160/148642852-9135cff7-2b3c-4b15-87ec-0dec8cbc5e73.jpg)

i don't know what hppn :(
I have tried "./setup.sh --install" again n again

**Comment by ZalgoNoise** [comment]
Sounds like out-of-date `apt` keys. Try running the commands below and re-install please

```
apt-key update ;
apt update -y
```

[Ref](https://askubuntu.com/questions/75565/why-am-i-getting-authentication-errors-for-packages-from-an-ubuntu-repository)

**Comment by Faris0520** [comment]
![Screenshot_2022-01-08-19-04-46-250_com termux](https://user-images.githubusercontent.com/65797160/148643527-46dd6299-2c33-401e-8e2f-e4e9c35aae93.jpg)
?

**Comment by ZalgoNoise** [comment]
I am not sure what is going on in your Termux installation but the issue here seems beyond this repo's scope.

I would suggest looking up the error messages you're getting (you still weren't able to update your apt keys) ;checking your internet connection (is it restrictive in any way?) ; and if you are able to backup your files, to reinstall Termux all together (clear all data from the app).

The issue here is not being able to verify the repo's signatures (making sure they are legit) and then some weird 502 errors (server errors) which I haven't seen yet.

**Comment by Faris0520** [comment]
mmm Okay
