### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by akramverus1** [adi1090x/termux-desktop#107]
when i run ./setup.sh --install
i get Permission denied
what can I do to fix this?

My phone is Reno 6 not rooted
![WhatsApp Image 2022-01-09 at 12 52 14](https://user-images.githubusercontent.com/97162554/148679192-6cfe0f84-a8f6-491a-96d7-87e4b3efae3f.jpeg)

**Comment by ZalgoNoise** [comment]
Your `setup.sh` is not an executable file, yet.

Run this command inside the downloaded folder:

```
chmod +x setup.sh
```

Then you can run it just fine.

**Comment by akramverus1** [comment]
> Your `setup.sh` is not an executable file, yet.
> 
> Run this command inside the downloaded folder:
> 
> ```
> chmod +x setup.sh
> ```
> 
> Then you can run it just fine.

i already did that ,still same permission denied

**Comment by ZalgoNoise** [comment]
I think you're trying to run these files from your Android's storage, or Downloads folder (correct me if I am wrong). Did you `git clone` the repo or downloaded it with Chrome or something? Because from the screenshot you clearly moved to `~/storage/downloads`.

If that is the case, you're running an executable _outside_ Termux's app folder. This is not possible (without root) nor is it advisable, either.

Please clone the repo with `git clone`, as listed in the instructions:

> Update termux packages and install git
```
pkg upgrade && pkg install git
```
> Clone this repository
```
git clone --depth=1 https://github.com/adi1090x/termux-desktop.git
```

**Comment by ezbluntz** [comment]
Check out my all in one Termux/Ubuntu 20.04 Frankenstein commit. 

Consists of a native termux DE with everything working (sound, internet etc) plus rooted ubuntu 20.04 server. 

# NO ROOT NEEDED!!   

https://github.com/ezbluntz/Terbuntu-Frankenstein-Desktop

![Screenshot_20220218-233459](https://user-images.githubusercontent.com/79003657/154811521-241e1912-142a-4dd3-9847-a2c1f13cfd85.png)

![Screenshot_20220218-233539](https://user-images.githubusercontent.com/79003657/154811532-b9b25114-396f-43a7-bb37-429b7cd00c88.png)
 
![Screenshot_20220218-234654](https://user-images.githubusercontent.com/79003657/154811548-fe0d94b0-484b-4163-99e9-1dcc54d46383.png)

![Screenshot_20220218-234859](https://user-images.githubusercontent.com/79003657/154811562-4942b772-8c51-41a4-9e12-724587db6e4b.png)

Super easy installation!!!
