### ISSUE TITLE
Stop after 20 seconds.... 

### ISSUE THREAD

**Issue by 0nsec** [adi1090x/termux-desktop#113]
![Screenshot_2022-02-10-18-05-42-08_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/99223413/153414306-085f691a-b85b-4ac5-b2f4-1fbc93bd8c3f.jpg)

Log file of localhost:1
Can any help me...

**Comment by ZalgoNoise** [comment]
Hi,

Thanks for the complete snippet of the vnc logfile, it seems that (on L63), `polybar` is crashing, which ends up terminating the Desktop Environment (ends on L64).

Looking into [polybar/include/cairo/context.hpp -- L31](https://github.com/polybar/polybar/blob/master/include/cairo/context.hpp#L31), the error thrown here is due to this module (cairo) not starting up successfully.

To simplify any troubleshooting particular to this module, can you try to uninstall and reinstall the repository to see if the issue persists? If it happens again, can you share more details on your device?

Lastly, once you reinstalled the repo, if you'd like to get rid of the `/etc/machine-id` errors you're seeing on L46 and L57, you can see #109, #110 and PR #111 which address this issue. After installing the repo, run the command below to create a `machine-id` and avoid such errors:

```
dbus-uuidgen --ensure=/data/data/com.termux/files/usr/etc/machine-id
```

**Comment by ezbluntz** [comment]
Check out my all in one Termux/Ubuntu 20.04 Frankenstein commit. 

Consists of a native termux DE with everything working (sound, internet etc) plus rooted ubuntu 20.04 server. 

# NO ROOT NEEDED!!   

https://github.com/ezbluntz/Terbuntu-Frankenstein-Desktop

![Screenshot_20220218-233459](https://user-images.githubusercontent.com/79003657/154811521-241e1912-142a-4dd3-9847-a2c1f13cfd85.png)

![Screenshot_20220218-233539](https://user-images.githubusercontent.com/79003657/154811532-b9b25114-396f-43a7-bb37-429b7cd00c88.png)
 
![Screenshot_20220218-234654](https://user-images.githubusercontent.com/79003657/154811548-fe0d94b0-484b-4163-99e9-1dcc54d46383.png)

![Screenshot_20220218-234859](https://user-images.githubusercontent.com/79003657/154811562-4942b772-8c51-41a4-9e12-724587db6e4b.png)

Super easy installation!!!

**Comment by gk98s** [comment]
just turn off battery optimisation
