### ISSUE TITLE
Bricked My Entire System

### ISSUE THREAD

**Issue by Ahmad-Is-A-Loser** [adi1090x/termux-desktop#67]
It literally bricked my entire system I can't install apps anymore open anything and when I restart it it doesn't open the launcher like the Google pixel launcher then when I restart it again it bootloops until I delete my bricked system and reinstall it again (Android 7.1.2 ARMEBI 7v 32Bit 1.5gb ram)

**Comment by batasu** [comment]
Is your device was rooted ?

**Comment by observerunion** [comment]
Yes it is

**Comment by Yisus7u7** [comment]
If your cell phone is. Root, using termux with root is dangerous, it wasn't his fault

**Comment by 130rne** [comment]
To anyone coming across this, don't use sudo/su. Termux is a user app, all data is in the user space, you're not accessing Android's system files. I was wondering why su commands were failing then I realized my mistake.

**Comment by FatVenom** [comment]
> It literally bricked my entire system I can't install apps anymore open anything and when I restart it it doesn't open the launcher like the Google pixel launcher then when I restart it again it bootloops until I delete my bricked system and reinstall it again (Android 7.1.2 ARMEBI 7v 32Bit 1.5gb ram)

On Termux website it's clearly written to use Termux GUI on Device with Android Version A9 or Above...
Broo it's your fault...You should read and research well before doing anything.

**Comment by ZalgoNoise** [comment]
> Android 7.1.2 ARMEBI 7v 32Bit 1.5gb ram

This is no longer a supported Android version for Termux, and this issue is unrelated to the installation of termux-desktop which **does not include any `su` / `tsu` commands nor does it install any root packages**. 

Please note that actions that you commit as a root user are your responsibility as they imply knowledge over the affected system. 

If you are still able to access your phone's recovery, you're still able to reinstall Android. This depends from phone to phone and unfortunately I am not familiar with particular steps to root and flash a Pixel phone. Maybe if you look up your phone model on XDA forums you may find a solution to do so and getting back to your device. Furthermore I **highly** recommend frequent backups if you're rooting your phone (and experimenting with superuser actions), from personal experience. 

Having this said, suggesting to close this issue since it's irrelevant to this repo (there are no root packages or actions handled)

**Comment by ezbluntz** [comment]
If you prefer Debian Bullseye, check TerBian Frankenstein

https://github.com/ezbluntz/Terbian-Frankenstein-DE

![Screenshot_20220220-004304](https://user-images.githubusercontent.com/79003657/154821581-d7d9abe5-39d4-45b5-ab34-c056ed067cbe.png)

![Screenshot_20220220-004345](https://user-images.githubusercontent.com/79003657/154821591-04361b11-a287-4a53-b187-8c2374050d31.png)

![Screenshot_20220220-004358](https://user-images.githubusercontent.com/79003657/154821605-b7f5e60f-f574-480b-b190-86cc5fc4c792.png)

![Screenshot_20220220-004410](https://user-images.githubusercontent.com/79003657/154821620-3495025a-d75a-4f04-b01e-6ec13dddbde0.png)

![Screenshot_20220220-004427](https://user-images.githubusercontent.com/79003657/154821629-d6d753cf-271c-4d0c-a330-9c9b47769f05.png)
