### ISSUE TITLE
Calc not installing

### ISSUE THREAD

**Issue by Javi3y** [adi1090x/termux-desktop#90]
![Screenshot_2021-09-23-12-33-45](https://user-images.githubusercontent.com/74869077/134481194-fe44a275-a83d-414c-ae5c-becd31fcb16c.png)
Termux-info
`Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.net stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-21 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-21 games stable
Updatable packages:
All packages up to date
Android version:
6.0
Kernel build information:
Linux localhost 3.10.84-g1ea7d46-00043-g47d4d65 #1 SMP PREEMPT Thu Aug 18 10:47:25 KST 2016 aarch64 Android
Device manufacturer:
LGE
Device model:
LG-H818`

**Comment by FatVenom** [comment]
Use Termux GUI on A9+.
As stated on Termux website.

**Comment by ZalgoNoise** [comment]
> Android version: 6.0 
> 
> Kernel build information: Linux localhost 3.10.84-g1ea7d46-00043-g47d4d65 

Like @FatVenom mentioned, this Android version is no longer supported by Termux, and the same requirements apply to this repo.

As a workaround, you can clone the repo and locally change the installed packages to fit the available ones for your phone's arch and version.

But note that `calc` is the 3rd package being installed. There may be plenty of occurrences like this where you may not be able to accomplish what this repo presents. If so, try in a newer phone.

Otherwise, the installed packages are [in an array just a bit below the banner](https://github.com/adi1090x/termux-desktop/blob/master/setup.sh#L56). On your local copy, you can remove the dependency causing issues and save the file, then running it again. See the example below without `calc`:

```
## Update, X11-repo, Program Installation
_pkgs=(bc bmon calcurse curl dbus desktop-file-utils elinks feh fontconfig-utils fsmon \
		geany git gtk2 gtk3 htop-legacy imagemagick jq leafpad man mpc mpd mutt ncmpcpp \
		ncurses-utils neofetch netsurf obconf openbox openssl-tool polybar ranger rofi \
		startup-notification termux-api thunar tigervnc vim wget xarchiver xbitmaps xcompmgr \
		xfce4-settings xfce4-terminal xmlstarlet xorg-font-util xorg-xrdb zsh)
```

It's important to underline that other, even more recent packages are likely not to be present just as well, unfortunately.
