### ISSUE TITLE
Not enough memory

### ISSUE THREAD

**Issue by iocmet** [adi1090x/termux-desktop#96]
I just don't have enough memory to install it on my phone 8 GB of internal memory on my tablet 16

Can I somehow put it on a SD card or something like that?

**Comment by Aridlvory** [comment]
No u can't... Idk if the code has a feature like that or somethin... But for sure. Termux can't write on external storages if u are not rooted...

**Comment by makarhuyaker** [comment]
> No u can't... Idk if the code has a feature like that or somethin... But for sure. Termux can't write on external storages if u are not rooted...

I have root :/

**Comment by makarhuyaker** [comment]
Hey?

**Comment by ZalgoNoise** [comment]
> > No u can't... Idk if the code has a feature like that or somethin... But for sure. Termux can't write on external storages if u are not rooted...
> 
> I have root :/

Unfortunately, Termux does not support installing software to your SD card, since the file system is different from the internal storage, and simply put will not allow the same set of features required to run Termux (FAT doesn't support symlinks). If you are able to format a partition of your SD as ext4 and be able to mount it, you may be able to accomplish this, but personally I've never tried it (even through quite some years with rooted phones running Termux).

You can see this information in the [official Termux docs](https://wiki.termux.com/wiki/Internal_and_external_storage):

> Shared storage as well as external storage is not suitable for installing software. Do not even try to move Termux directories like $HOME or $PREFIX onto this kind of storage. Such option is only available for advanced users who have rooted device and are familiar with customization of partitions and file system on their external storage. Use of adoptable storage will not make your external SD card compatible with Termux, it is effectively same as shared storage (EXT4/F2FS with FAT32/exFAT compatible overlay).

**Comment by makarhuyaker** [comment]
I already tried to transfer $home, etc. to the SD card, but nothing worked

**Comment by Anonymous2716** [comment]
Reformat external SDcard . Set your settings to install apps on SD card that might work .

**Comment by ZalgoNoise** [comment]
Termux does not work when non-(external-)storage files or folders are moved or installed in external storage such as the SD card.

See [Termux's Wiki](https://wiki.termux.com/wiki/Internal_and_external_storage) for context.

That being the case, there is no solution other than:

- Making up enough space in the internal storage (1,5~2GB)
- Installing in a different device.

Note that, if these are older devices (due to their total internal storage amount), you may face performance issues when running a desktop environment + VNC server (+ VNC client maybe) on the same device.

I understand you're trying to juice them, but even if this doesn't work you can still take advantage of the device using a CLI. I still use my Galaxy J5 (without termux-desktop).

Lastly, you can always fork / submit a PR if you find a solution for a more lightweight GUI / desktop installation. You can use PR #104 as reference for a Dockerfile so you don't need to clear data on your phone's app all the time.

**Comment by makarhuyaker** [comment]
ok
